# config/env.yaml
dev:
  project_id: "lakehouse-486419"
  location: "europe-west1"
  bq:
    raw_dataset: "raw_ext_dev"
    curated_dataset: "curated_dev"
  dataform:
    repo: "lakehouse-dev-dataform"
    workflow: "wf-prod-weekdays"

staging:
  project_id: "lakehouse-stg-486419"
  location: "europe-west1"
  bq:
    raw_dataset: "raw_ext_staging"
    curated_dataset: "curated_staging"
  dataform:
    repo: "lakehouse-staging-dataform"
    workflow: "wf-prod-weekdays"

prod:
  project_id: "lakehouse-prd-486419"
  location: "europe-west1"
  bq:
    raw_dataset: "raw_ext_prod"
    curated_dataset: "curated_prod"
  dataform:
    repo: "lakehouse-prod-dataform"
    workflow: "wf-prod-weekdays"