profiles:
  dev_small:
    properties:
      spark.driver.cores: "4"
      spark.driver.memory: "4g"

      spark.executor.instances: "2"
      spark.executor.cores: "4"
      spark.executor.memory: "4g"

      spark.dataproc.driver.disk.size: "250g"
      spark.dataproc.executor.disk.size: "250g"

      spark.dynamicAllocation.executorAllocationRatio: "0.2"


  dev_medium:
    properties:
      spark.driver.cores: "4"
      spark.driver.memory: "8g"
      spark.executor.instances: "2"
      spark.executor.cores: "4"
      spark.executor.memory: "8g"
      spark.dynamicAllocation.executorAllocationRatio: "0.3"


  dev_tiny:
    properties:
      spark.driver.cores: "1"
      spark.driver.memory: "2g"
      spark.executor.instances: "2"
      spark.executor.cores: "1"
      spark.executor.memory: "2g"
      spark.dynamicAllocation.executorAllocationRatio: "0.1"