name: Terraform (staging) - plan

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan-staging:
    runs-on: ubuntu-latest
    environment: staging   # IMPORTANT si tes secrets sont dans Environment "staging"

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Auth WIF (ADC) -> crée un fichier credentials utilisé par Terraform provider google
      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER_STAGING }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT_STAGING }}
          create_credentials_file: true
          export_environment_variables: true

      # gcloud (facultatif mais utile)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_STAGING }}

      - name: Debug - identity + project (safe)
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
          echo "Active project:"
          gcloud config get-value project
          echo "Active account:"
          gcloud config get-value account
          echo "gcloud auth list:"
          gcloud auth list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (staging backend)
        run: terraform init -backend-config=envs/staging/backend.hcl -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (staging)
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID_STAGING }}
        run: terraform plan -var-file=envs/staging/terraform.tfvars