name: Terraform - Staging (Plan)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-staging.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan-staging:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      GOOGLE_CLOUD_PROJECT: "lakehouse-stg-486419"
      PROJECT_ID: "lakehouse-stg-486419"
      STAGING_SA: "sa-github-cicd-staging@lakehouse-stg-486419.iam.gserviceaccount.com"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Auth GitHub -> GCP via Workload Identity Federation
      - name: Auth to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          create_credentials_file: true
          export_environment_variables: true
          workload_identity_provider: "${{ secrets.GCP_WIF_PROVIDER_STAGING }}"
          service_account: "sa-github-cicd-staging@lakehouse-stg-486419.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "lakehouse-stg-486419"

      # Debug utile (à garder tant que ce n’est pas stable)
      - name: Debug - who is Terraform actually using?
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
          echo "== creds file (safe fields) =="
          sudo apt-get update -y >/dev/null 2>&1 || true
          sudo apt-get install -y jq >/dev/null 2>&1 || true
          cat "$GOOGLE_APPLICATION_CREDENTIALS" | jq -r '.type, .audience, .subject_token_type, (.service_account_impersonation_url // "NO_IMPERSONATION_URL")'

          echo "== gcloud auth list =="
          gcloud auth list

          echo "== gcloud config list =="
          gcloud config list

          echo "== tokeninfo (email/aud/azp) =="
          ACCESS_TOKEN="$(gcloud auth print-access-token)"
          curl -s "https://oauth2.googleapis.com/tokeninfo?access_token=${ACCESS_TOKEN}" | jq -r '.email,.aud,.azp'

          echo "== SA expected =="
          echo "${STAGING_SA}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (staging backend)
        run: terraform init -backend-config=envs/staging/backend.hcl -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (staging)
        run: terraform plan -var-file=envs/staging/terraform.tfvars