name: Terraform (staging) - plan

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  # ✅ Job PR : pas de secrets, pas d'auth, juste qualité Terraform
  terraform-ci:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (local, no backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate


  # ✅ Job main : auth WIF + backend GCS + plan staging
  terraform-plan-staging:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    environment: staging   # IMPORTANT si tes secrets sont dans Environment "staging"

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Fail fast if secrets missing
        run: |
          [ -n "${{ secrets.GCP_WIF_PROVIDER_STAGING }}" ] || (echo "❌ Missing secret: GCP_WIF_PROVIDER_STAGING" && exit 1)
          [ -n "${{ secrets.GCP_WIF_SERVICE_ACCOUNT_STAGING }}" ] || (echo "❌ Missing secret: GCP_WIF_SERVICE_ACCOUNT_STAGING" && exit 1)
          [ -n "${{ secrets.GCP_PROJECT_ID_STAGING }}" ] || (echo "❌ Missing secret: GCP_PROJECT_ID_STAGING" && exit 1)

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER_STAGING }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT_STAGING }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_STAGING }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (staging backend)
        run: terraform init -backend-config=envs/staging/backend.hcl -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (staging)
        run: terraform plan -var-file=envs/staging/terraform.tfvars